<?php

declare(strict_types=1);

namespace PhpTramp\Tests\Report;

use PhpTramp\Chain\Finding;
use PhpTramp\Chain\Hop;
use PhpTramp\Chain\TerminalKind;
use PhpTramp\Report\AnsiStyler;
use PhpTramp\Report\NullStyler;
use PhpTramp\Report\Paths;
use PhpTramp\Report\PrettyReporter;
use PhpTramp\Report\Thresholds;
use PHPUnit\Framework\TestCase;

/**
 * PrettyReporter layout fixtures, injected with NullStyler so they assert
 * pure text (grouping, dividers, file headers, labels, summary) with zero
 * ANSI noise. The color codes themselves are pinned in AnsiStylerTest.
 *
 * The method column is aligned exactly like TextReporter: each row's
 * "FQMN($param)" is padded to the longest method in the finding, then a
 * 2-space gap, then the location. The label column is at least MIN_LABEL_WIDTH
 * (8) wide, matching TextReporter. Per-finding text, threshold filtering,
 * terminal detection, and the summary shape mirror TextReporter exactly; the
 * pretty format layers file-grouping (alphabetical), a divider, file headers,
 * and styling on top.
 *
 * Fixtures were generated by running the implementation with NullStyler, then
 * inspected against the semantic rules (header keyword by severity, alphabetical
 * file order, divider placement, summary split iff warnLimit !== null). The
 * underlying per-finding semantics are independently pinned by TextReporterTest.
 */
final class PrettyReporterTest extends TestCase
{
    public function testEmptyFindingsRendersSuccessLine(): void
    {
        $reporter = new PrettyReporter(
            new Thresholds(3, null),
            new Paths('/nonexistent-root'),
            false,
            new NullStyler(),
        );

        self::assertSame("No tramp data found (limit: 3 hops).\n", $reporter->render([]));
    }

    public function testRendersSingleFindingWithFileHeaderAndDividerAndSummary(): void
    {
        // hops=3, 4-node chain (3 forward + 1 terminal), Thresholds(3, null) -> Error.
        $chain = [
            new Hop('Demo\Controller::handle', 'Demo\Controller', 'src/Demo.php', 12, 14),
            new Hop('Demo\ServiceA::process', 'Demo\ServiceA', 'src/Demo.php', 18, 20),
            new Hop('Demo\ServiceB::run', 'Demo\ServiceB', 'src/Demo.php', 24, 26),
            new Hop('Demo\Mailer::__construct', 'Demo\Mailer', 'src/Demo.php', 32, null),
        ];
        $finding = new Finding(
            'config',
            'Demo\Controller::handle',
            'Demo\Mailer::__construct',
            TerminalKind::Stored,
            3,
            $chain,
            4,
            [],
            [],
        );

        $expected = <<<'TXT'
src/Demo.php

FINDING  $config: 3 pass-through hops across 4 classes
  origin    Demo\Controller::handle($config)   src/Demo.php:12
  hop 2     Demo\ServiceA::process($config)    src/Demo.php:18
  hop 3     Demo\ServiceB::run($config)        src/Demo.php:24
  terminal  Demo\Mailer::__construct($config)  src/Demo.php:32  (stored)

----------------------------------------------------------------

1 finding (limit: 3 hops).

TXT;

        $reporter = new PrettyReporter(
            new Thresholds(3, null),
            new Paths('/nonexistent-root'),
            false,
            new NullStyler(),
        );

        self::assertSame($expected, $reporter->render([$finding]));
    }

    public function testRendersWarningHeaderAtWarnLimit(): void
    {
        // hops=1, Thresholds(3, 1) -> Warning (hops >= warnLimit). Summary SPLITS
        // (warnLimit !== null): '1 finding (0 errors, 1 warning; ...)'.
        $chain = [
            new Hop('Demo\A::go', 'Demo\A', 'src/A.php', 5, 7),
            new Hop('Demo\B::step', 'Demo\B', 'src/B.php', 9, null),
        ];
        $finding = new Finding('cfg', 'Demo\A::go', 'Demo\B::step', TerminalKind::Used, 1, $chain, 2, [], []);

        $expected = <<<'TXT'
src/A.php

WARNING  $cfg: 1 pass-through hop across 2 classes
  origin    Demo\A::go($cfg)    src/A.php:5
  terminal  Demo\B::step($cfg)  src/B.php:9  (used)

----------------------------------------------------------------

1 finding (0 errors, 1 warning; limit: 3 hops, warn-limit: 1 hop).

TXT;

        $reporter = new PrettyReporter(
            new Thresholds(3, 1),
            new Paths('/nonexistent-root'),
            false,
            new NullStyler(),
        );

        self::assertSame($expected, $reporter->render([$finding]));
    }

    public function testMarksChangedNonTerminalHopWithYoursAnnotation(): void
    {
        // Same as the single-finding case but hop 2 has changed=true -> *YOURS*.
        $chain = [
            new Hop('Demo\Controller::handle', 'Demo\Controller', 'src/Demo.php', 12, 14),
            new Hop('Demo\ServiceA::process', 'Demo\ServiceA', 'src/Demo.php', 18, 20, true),
            new Hop('Demo\ServiceB::run', 'Demo\ServiceB', 'src/Demo.php', 24, 26),
            new Hop('Demo\Mailer::__construct', 'Demo\Mailer', 'src/Demo.php', 32, null),
        ];
        $finding = new Finding(
            'config',
            'Demo\Controller::handle',
            'Demo\Mailer::__construct',
            TerminalKind::Stored,
            3,
            $chain,
            4,
            [],
            [],
        );

        $expected = <<<'TXT'
src/Demo.php

FINDING  $config: 3 pass-through hops across 4 classes
  origin    Demo\Controller::handle($config)   src/Demo.php:12
  hop 2     Demo\ServiceA::process($config)    src/Demo.php:18  *YOURS*
  hop 3     Demo\ServiceB::run($config)        src/Demo.php:24
  terminal  Demo\Mailer::__construct($config)  src/Demo.php:32  (stored)

----------------------------------------------------------------

1 finding (limit: 3 hops).

TXT;

        $reporter = new PrettyReporter(
            new Thresholds(3, null),
            new Paths('/nonexistent-root'),
            false,
            new NullStyler(),
        );

        self::assertSame($expected, $reporter->render([$finding]));
    }

    public function testGroupsByFileAlphabeticallyAndSortsWithinFileByFirstHopLine(): void
    {
        // Three findings, all hops=1, Thresholds(1, null) so all are reported as Error.
        // Input order scrambled: [Other, Demo-line-12, Demo-line-5]. Expected group
        // order is ALPHABETICAL (src/Demo.php before src/Other.php); within
        // src/Demo.php, sorted by first hop line (5 before 12).
        $demoEarly = new Finding(
            'early',
            'Demo\A::go',
            'Demo\B::sink',
            TerminalKind::Used,
            1,
            [
                new Hop('Demo\A::go', 'Demo\A', 'src/Demo.php', 5, 7),
                new Hop('Demo\B::sink', 'Demo\B', 'src/Demo.php', 9, null),
            ],
            2,
            [],
            [],
        );
        $demoLate = new Finding(
            'late',
            'Demo\C::run',
            'Demo\D::end',
            TerminalKind::Used,
            1,
            [
                new Hop('Demo\C::run', 'Demo\C', 'src/Demo.php', 12, 14),
                new Hop('Demo\D::end', 'Demo\D', 'src/Demo.php', 16, null),
            ],
            2,
            [],
            [],
        );
        $other = new Finding(
            'flag',
            'Demo\X::go',
            'Demo\Y::sink',
            TerminalKind::Used,
            1,
            [
                new Hop('Demo\X::go', 'Demo\X', 'src/Other.php', 5, 7),
                new Hop('Demo\Y::sink', 'Demo\Y', 'src/Other.php', 9, null),
            ],
            2,
            [],
            [],
        );

        $expected = <<<'TXT'
src/Demo.php

FINDING  $early: 1 pass-through hop across 2 classes
  origin    Demo\A::go($early)    src/Demo.php:5
  terminal  Demo\B::sink($early)  src/Demo.php:9  (used)

FINDING  $late: 1 pass-through hop across 2 classes
  origin    Demo\C::run($late)  src/Demo.php:12
  terminal  Demo\D::end($late)  src/Demo.php:16  (used)

----------------------------------------------------------------

src/Other.php

FINDING  $flag: 1 pass-through hop across 2 classes
  origin    Demo\X::go($flag)    src/Other.php:5
  terminal  Demo\Y::sink($flag)  src/Other.php:9  (used)

----------------------------------------------------------------

3 findings (limit: 1 hop).

TXT;

        $reporter = new PrettyReporter(
            new Thresholds(1, null),
            new Paths('/nonexistent-root'),
            false,
            new NullStyler(),
        );

        self::assertSame($expected, $reporter->render([$other, $demoLate, $demoEarly]));
    }

    public function testRendersTruncatedChainWithNoteLineAndNoTerminal(): void
    {
        // hops=2, 2-node chain (no terminal — Truncated keeps none),
        // Thresholds(2, null) -> Error. count(chain)=2, hops=2 -> no terminal node.
        $chain = [
            new Hop('Demo\A::go', 'Demo\A', 'src/A.php', 5, 7),
            new Hop('Demo\B::step', 'Demo\B', 'src/B.php', 9, 11),
        ];
        $finding = new Finding(
            'cfg',
            'Demo\A::go',
            null,
            TerminalKind::Truncated,
            2,
            $chain,
            2,
            ['truncated: 2 implementations'],
            [],
        );

        $expected = <<<'TXT'
src/A.php

FINDING  $cfg: 2 pass-through hops across 2 classes
  origin    Demo\A::go($cfg)    src/A.php:5
  hop 2     Demo\B::step($cfg)  src/B.php:9
  note      truncated: 2 implementations

----------------------------------------------------------------

1 finding (limit: 2 hops).

TXT;

        $reporter = new PrettyReporter(
            new Thresholds(2, null),
            new Paths('/nonexistent-root'),
            false,
            new NullStyler(),
        );

        self::assertSame($expected, $reporter->render([$finding]));
    }

    public function testExplainBlockRenderedWhenExplainTrue(): void
    {
        // hops=1, Thresholds(1, null) -> Error. explain:true shows the trace block.
        $chain = [
            new Hop('Demo\A::go', 'Demo\A', 'src/A.php', 5, 7),
            new Hop('Demo\B::sink', 'Demo\B', 'src/A.php', 9, null),
        ];
        $finding = new Finding(
            'cfg',
            'Demo\A::go',
            'Demo\B::sink',
            TerminalKind::Used,
            1,
            $chain,
            2,
            [],
            ['resolved Demo\A::go -> Demo\B::sink via interface Demo\I'],
        );

        $expected = <<<'TXT'
src/A.php

FINDING  $cfg: 1 pass-through hop across 2 classes
  origin    Demo\A::go($cfg)    src/A.php:5
  terminal  Demo\B::sink($cfg)  src/A.php:9  (used)
  explain:
    resolved Demo\A::go -> Demo\B::sink via interface Demo\I

----------------------------------------------------------------

1 finding (limit: 1 hop).

TXT;

        $reporter = new PrettyReporter(
            new Thresholds(1, null),
            new Paths('/nonexistent-root'),
            true,
            new NullStyler(),
        );

        self::assertSame($expected, $reporter->render([$finding]));
    }

    public function testWarnVsErrorSummarySplit(): void
    {
        // $a: hops=3, 4-node chain (3 forward + terminal), Thresholds(3, 1) -> Error.
        // $b: hops=1, 2-node chain, Thresholds(3, 1) -> Warning (>= warnLimit, < limit).
        // Both first hops at src/A.php:5; stable sort preserves input order: $a then $b.
        // Summary SPLITS (warnLimit=1 !== null): '2 findings (1 error, 1 warning; ...)'.
        $error = new Finding(
            'a',
            'Demo\A::go',
            'Demo\D::sink',
            TerminalKind::Used,
            3,
            [
                new Hop('Demo\A::go', 'Demo\A', 'src/A.php', 5, 7),
                new Hop('Demo\B::step', 'Demo\B', 'src/A.php', 9, 11),
                new Hop('Demo\C::mid', 'Demo\C', 'src/A.php', 13, 15),
                new Hop('Demo\D::sink', 'Demo\D', 'src/A.php', 17, null),
            ],
            4,
            [],
            [],
        );
        $warning = new Finding(
            'b',
            'Demo\A::go',
            'Demo\C::sink',
            TerminalKind::Used,
            1,
            [
                new Hop('Demo\A::go', 'Demo\A', 'src/A.php', 5, 7),
                new Hop('Demo\C::sink', 'Demo\C', 'src/A.php', 13, null),
            ],
            2,
            [],
            [],
        );

        $expected = <<<'TXT'
src/A.php

FINDING  $a: 3 pass-through hops across 4 classes
  origin    Demo\A::go($a)    src/A.php:5
  hop 2     Demo\B::step($a)  src/A.php:9
  hop 3     Demo\C::mid($a)   src/A.php:13
  terminal  Demo\D::sink($a)  src/A.php:17  (used)

WARNING  $b: 1 pass-through hop across 2 classes
  origin    Demo\A::go($b)    src/A.php:5
  terminal  Demo\C::sink($b)  src/A.php:13  (used)

----------------------------------------------------------------

2 findings (1 error, 1 warning; limit: 3 hops, warn-limit: 1 hop).

TXT;

        $reporter = new PrettyReporter(
            new Thresholds(3, 1),
            new Paths('/nonexistent-root'),
            false,
            new NullStyler(),
        );

        self::assertSame($expected, $reporter->render([$error, $warning]));
    }

    /**
     * Within-file sort uses the FIRST hop's line, not any later hop's. Two
     * findings in the same file where finding A starts earlier (line 5) but
     * its terminal sits later (line 20) than finding B's terminal (line 15).
     * Correct sort by chain[0]->line puts A before B; sorting by chain[1]
     * would flip them. Input is deliberately reversed so a no-op sort would
     * also fail the assertion.
     */
    public function testWithinFileSortUsesFirstHopLineNotLaterHops(): void
    {
        $earlyStartLateTerminal = new Finding(
            'a',
            'Demo\A::go',
            'Demo\B::sink',
            TerminalKind::Used,
            1,
            [
                new Hop('Demo\A::go', 'Demo\A', 'src/A.php', 5, null),
                new Hop('Demo\B::sink', 'Demo\B', 'src/A.php', 20, null),
            ],
            2,
            [],
            [],
        );
        $lateStartEarlyTerminal = new Finding(
            'b',
            'Demo\C::run',
            'Demo\D::end',
            TerminalKind::Used,
            1,
            [
                new Hop('Demo\C::run', 'Demo\C', 'src/A.php', 10, null),
                new Hop('Demo\D::end', 'Demo\D', 'src/A.php', 15, null),
            ],
            2,
            [],
            [],
        );

        $expected = <<<'TXT'
src/A.php

FINDING  $a: 1 pass-through hop across 2 classes
  origin    Demo\A::go($a)    src/A.php:5
  terminal  Demo\B::sink($a)  src/A.php:20  (used)

FINDING  $b: 1 pass-through hop across 2 classes
  origin    Demo\C::run($b)  src/A.php:10
  terminal  Demo\D::end($b)  src/A.php:15  (used)

----------------------------------------------------------------

2 findings (limit: 1 hop).

TXT;

        $reporter = new PrettyReporter(
            new Thresholds(1, null),
            new Paths('/nonexistent-root'),
            false,
            new NullStyler(),
        );

        self::assertSame($expected, $reporter->render([$lateStartEarlyTerminal, $earlyStartLateTerminal]));
    }

    /**
     * explain:false suppresses the trace block even when the finding carries
     * a non-empty trace. Guards the `! $this->explain || trace === []` guard
     * against an `&&` mutation that would render the block whenever a trace
     * exists, regardless of the explain flag.
     */
    public function testExplainBlockSuppressedWhenExplainFalseEvenWithTrace(): void
    {
        $chain = [
            new Hop('Demo\A::go', 'Demo\A', 'src/A.php', 5, 7),
            new Hop('Demo\B::sink', 'Demo\B', 'src/A.php', 9, null),
        ];
        $finding = new Finding(
            'cfg',
            'Demo\A::go',
            'Demo\B::sink',
            TerminalKind::Used,
            1,
            $chain,
            2,
            [],
            ['resolved Demo\A::go -> Demo\B::sink via interface Demo\I'],
        );

        $expected = <<<'TXT'
src/A.php

FINDING  $cfg: 1 pass-through hop across 2 classes
  origin    Demo\A::go($cfg)    src/A.php:5
  terminal  Demo\B::sink($cfg)  src/A.php:9  (used)

----------------------------------------------------------------

1 finding (limit: 1 hop).

TXT;

        $reporter = new PrettyReporter(
            new Thresholds(1, null),
            new Paths('/nonexistent-root'),
            false,
            new NullStyler(),
        );

        self::assertSame($expected, $reporter->render([$finding]));
    }

    /**
     * With AnsiStyler injected, `*YOURS*` must route through `annotation()`
     * (bold-magenta) and `(stored)` through `terminalKind()` (dim-green). The
     * NullStyler fixtures cannot distinguish the two routes because both
     * return their input unchanged; this exact-byte assertion pins the
     * ternary in hopLine() against a branch swap.
     */
    public function testAnsiStylerRoutesYoursToAnnotationAndTerminalKindToTerminalKind(): void
    {
        $chain = [
            new Hop('Demo\Controller::handle', 'Demo\Controller', 'src/Demo.php', 12, 14),
            new Hop('Demo\ServiceA::process', 'Demo\ServiceA', 'src/Demo.php', 18, 20, true),
            new Hop('Demo\ServiceB::run', 'Demo\ServiceB', 'src/Demo.php', 24, 26),
            new Hop('Demo\Mailer::__construct', 'Demo\Mailer', 'src/Demo.php', 32, null),
        ];
        $finding = new Finding(
            'config',
            'Demo\Controller::handle',
            'Demo\Mailer::__construct',
            TerminalKind::Stored,
            3,
            $chain,
            4,
            [],
            [],
        );

        $expected = <<<TXT
\e[1;34msrc/Demo.php\e[0m

\e[1;31mFINDING\e[0m  \$\e[1mconfig\e[0m: 3 pass-through hops across 4 classes
  \e[2morigin  \e[0m  Demo\Controller::handle(\$\e[36mconfig\e[0m)   \e[2msrc/Demo.php:12\e[0m
  \e[2mhop 2   \e[0m  Demo\ServiceA::process(\$\e[36mconfig\e[0m)    \e[2msrc/Demo.php:18\e[0m  \e[1;35m*YOURS*\e[0m
  \e[2mhop 3   \e[0m  Demo\ServiceB::run(\$\e[36mconfig\e[0m)        \e[2msrc/Demo.php:24\e[0m
  \e[2mterminal\e[0m  Demo\Mailer::__construct(\$\e[36mconfig\e[0m)  \e[2msrc/Demo.php:32\e[0m  \e[2;32m(stored)\e[0m

\e[2m----------------------------------------------------------------\e[0m

\e[1m1 finding (limit: 3 hops).\e[0m

TXT;

        $reporter = new PrettyReporter(
            new Thresholds(3, null),
            new Paths('/nonexistent-root'),
            false,
            new AnsiStyler(),
        );

        self::assertSame($expected, $reporter->render([$finding]));
    }
}
